# roadmap_tool.py
from agents import function_tool

@function_tool
def get_career_roadmap(field: str) -> str:
    maps ={
        "software_development": "1. Learn programming languages (Python, JavaScript)\n2. Build projects (web apps, mobile apps)\n3. Contribute to open source\n4. Learn version control (Git)\n5. Explore frameworks (React, Django)\n6. Understand databases (SQL, NoSQL)\n7. Master algorithms and data structures\n8. Prepare for technical interviews",
        "data_science": "2. Learn statistics and probability\n2. Master Python or R\n3. Get comfortable with data manipulation (Pandas)\n4. Learn machine learning basics\n5. Work on data visualization (Matplotlib, Seaborn)\n6. Build a portfolio with projects\n7. Understand big data technologies (Hadoop, Spark)\n8. Prepare for data science interviews",
        "cyber_security": "3. Understand networking fundamentals\n2. Learn about operating systems (Linux, Windows)\n3. Study security principles and practices\n4. Get hands-on with penetration testing tools\n5. Explore cryptography basics\n6. Participate in Capture The Flag (CTF) challenges\n7. Stay updated with the latest security trends\n8. Prepare for cybersecurity certifications",
        "cloud_computing": "4. Learn cloud fundamentals (AWS, Azure, GCP)\n2. Understand virtualization and containerization\n3. Get hands-on with cloud services (EC2, S3, Lambda)\n4. Explore DevOps practices\n5. Learn about infrastructure as code (Terraform)\n6. Build and deploy applications in the cloud\n7. Understand cloud security best practices\n8. Prepare for cloud certifications",
        "networking": "5. Learn networking basics (TCP/IP, OSI model)\n2. Understand routing and switching concepts\n3. Get hands-on with network configuration (Cisco, Juniper)\n4. Explore network security principles\n5. Study wireless networking technologies\n6. Learn about network monitoring tools\n7. Participate in networking labs and simulations\n8. Prepare for networking certifications",
        "artificial_intelligence": "6. Learn machine learning algorithms\n2. Undeandrstand neural networks and deep learning\n3. Get hands-on with AI frameworks (TensorFlow, PyTorch)\n4. Explore natural language processing (NLP)\n5. Work on AI projects and case studies\n6. Stay updated with AI research papers\n7. Participate in AI competitions (Kaggle)\n8. Prepare for AI-related roles",
        "graphic design": "7. Master design software (Adobe Photoshop, Illustrator)\n2. Learn about color theory and typography\n3. Get hands-on with UI/UX design principles\n4. Build a portfolio with design projects\n5. Explore web and mobile design trends\n6. Understand branding and visual identity\n7. Participate in design challenges\n8. Prepare for graphic design roles",
        "digital_marketing": "8. Learn SEO and SEM strategies\n2. Understand social media marketing\n3. Get hands-on with content creation\n4. Explore email marketing techniques\n5. Study analytics tools (Google Analytics)\n6. Build a personal brand online\n7. Stay updated with digital marketing trends\n8. Prepare for digital marketing roles",
        "project_management": "9. Understand project management methodologies (Agile, Scrum)\n2. Learn about project planning and scheduling\n3. Get hands-on with project management tools (Jira, Trello)\n4. Explore risk management strategies\n5. Develop leadership and communication skills\n6. Build a portfolio of managed projects\n7. Stay updated with industry best practices\n8. Prepare for project management certifications",
        "mobile_app_development": "10. Learn mobile development frameworks (React Native, Flutter)\n2. Understand mobile UI/UX design principles\n3. Get hands-on with app development (iOS, Android)\n4. Explore app deployment processes\n5. Study mobile security best practices\n6. Build a portfolio of mobile apps\n7. Stay updated with mobile development trends\n8. Prepare for mobile app development roles",
        "game_development": "11. Learn game development engines (Unity, Unreal Engine)\n2. Understand game design principles\n3. Get hands-on with 2D/3D game development\n4. Explore game physics and AI\n5. Study game monetization strategies\n6. Build a portfolio of games\n7. Participate in game jams\n8. Prepare for game development roles",
        "business_analysis": "12. Understand business analysis fundamentals\n2. Learn requirements gathering techniques\n3. Get hands-on with data analysis tools (Excel, SQL)\n4. Explore process modeling and improvement\n5. Develop stakeholder management skills\n6. Build a portfolio of business analysis projects\n7. Stay updated with industry trends\n8. Prepare for business analyst roles",
        "data_architecture": "13. Learn data architecture principles\n2. Understand data modeling techniques\n3. Get hands-on with database design\n4. Explore data integration strategies\n5. Study data governance and quality\n6. Build a portfolio of data architecture projects\n7. Stay updated with industry trends\n8. Prepare for data architecture roles",
        "blockchain_development": "14. Understand blockchain fundamentals\n2. Learn smart contract development (Solidity)\n3. Get hands-on with blockchain platforms (Ethereum, Hyperledger)\n4. Explore decentralized applications (dApps)\n5. Study blockchain security best practices\n6. Build a portfolio of blockchain projects\n7. Stay updated with blockchain trends\n8. Prepare for blockchain development roles",
        "web_development": "15. Learn web development frameworks (React, Angular)\n2. Understand front-end and back-end development\n3. Get hands-on with web design principles\n4. Explore responsive design techniques\n5. Study web performance optimization\n6. Build a portfolio of web applications\n7. Stay updated with web development trends\n8. Prepare for web development roles",
        "data_engineering": "16. Learn data engineering fundamentals\n2. Understand ETL processes and tools\n3. Get hands-on with big data technologies (Hadoop, Spark)\n4. Explore data warehousing concepts\n5. Study data pipeline design\n6. Build a portfolio of data engineering projects\n7. Stay updated with industry trends\n8. Prepare for data engineering roles",
        "cyber_physical_systems": "17. Understand cyber-physical systems fundamentals\n2. Learn about IoT devices and protocols\n3. Get hands-on with embedded systems programming\n4. Explore real-time data processing\n5. Study system integration techniques\n6. Build a portfolio of cyber-physical projects\n7. Stay updated with industry trends\n8. Prepare for cyber-physical systems roles",
    } 

    return maps.get(field.lower(), "Career roadmap not found for the specified field.")